sudo: enabled
osx_image: xcode9.2
language: objective-c
xcode_project: RxMVVM.xcodeproj # path to your xcodeproj folder
xcode_scheme: RxMVVM

cache:
  directories:
  - Carthage

before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - travis_wait 30 carthage bootstrap --cache-builds --platform ios